#SPDX-License-Identifier: MIT-0
---
# tasks file for configure-startup-script
#name: Setup autostart for start.sh
#hosts: localhost
- name: Make start.sh executable
  file:
    path: "{{ role_path }}/files/start.sh"
    mode: '0755'

  
- name: Create autostart directory
  file:
    path: ~/.config/autostart/
    state: directory
    mode: '0755'

  
- name: Copy start.sh to config directory
  copy:
    src: "{{ role_path }}/files/start.sh"
    dest: ~/.config/start.sh
    mode: '0755'

  
- name: Copy start_script.desktop to autostart directory
  copy:
    src: "{{ role_path }}/files/start_script.desktop"
    dest: ~/.config/autostart/start_script.desktop
