- name: Update apt cache
  apt:
    update_cache: yes
- name: "Ensure that open-vm-tools packages are installed"
  package:
    name:
      - open-vm-tools-desktop 
      - open-vm-tools
      - fuse
    state: latest
  become: true
  become_method: sudo
- name: "Install docker"
  package:
    name:
      - docker.io
    state: latest
  become: true
  become_method: sudo
- name: "Enable and start Docker service"
  systemd:
    name: docker
    enabled: yes
    state: started

